name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm install
        cd client && npm install
        cd ../server && npm install

    - name: Build client
      run: |
        cd client
        npm run build

    - name: Build server
      run: |
        cd server
        npm run build

    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd /var/www/mail.byzand.online
          git pull origin main
          npm install
          cd client && npm install && npm run build && cd ..
          cd server && npm install && npm run build && cd ..
          pm2 restart byzand-mail
          sudo systemctl reload nginx
